name: hivertradercourse

services:
  postgres:
    image: postgres
    container_name: hivertradercourse-postgres
    environment:
      POSTGRES_DB: hivertradercourse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - hivertradercourse_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: quay.io/minio/aistor/minio
    container_name: hivertradercourse-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_LICENSE: /opt/minio/minio.license
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - hivertradercourse_minio_data:/data
      - ./minio.license:/opt/minio/minio.license:ro
    restart: unless-stopped

volumes:
  hivertradercourse_postgres_data:
  hivertradercourse_minio_data:
